site_name: Geocodes Documentation
repo_url: https://github.com/earthcube/geocodes
edit_uri: blob/docs/docs/
theme:
#  name: 'readthedocs'
  name: material
  features:
#    - content.code.copy
    - navigation.sections
markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences


plugins:
  - search
  # literate_nav must load after multirepo for the features to be available.
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
  -  mermaid2
  - literate-nav
  #https://pypi.org/project/mkdocs-jupyter/
  -  mkdocs-jupyter
  - callouts
nav:
  - How To Create a Geocodes Server: index.md
  - List of services: stack_machines.md
  - Setup:
      - Base Machine: setup_base_machine_configuration.md
      - Create Services Containers: setup_geocodes_services_containers.md
      - Create Gleaner Containers: setup_gleaner_container.md
      - Load Data: setup_indexing_with_gleanerio.md
      - Create Geocodes UI Containers: setup_geocodes_ui_containers.md
      - Creating a Community Instance (Tenant): tenant
  - Load and Manage Production Data:
      - Production: production
      - Creating and Loading Production: production/creatingAndLoadingProduction.md
      - Manage Services: production/managing_services.md
  - Testing and Validation:
     - Some SPARQL Queries: production/sparql.md
     - Testing: indexing_with_gleanerio_for_testing.md
  - Tooling:
      - Install Glcon: install_glcon.md
  - Troubleshooting: troubleshooting.md
