site_name: Geocodes Documentation
repo_url: https://github.com/earthcube/geocodes
edit_uri: blob/docs/docs/
theme:
#  name: 'readthedocs'
  name: material
  features:
#    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.path
    - navigation.indexes
markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences


plugins:
  - glightbox
  - search
  # literate_nav must load after multirepo for the features to be available.
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
  -  mermaid2
  - literate-nav
  #https://pypi.org/project/mkdocs-jupyter/
  -  mkdocs-jupyter
  - callouts

#extra_javascript:
#  - https://unpkg.com/mermaid/dist/mermaid.min.js
#  -
nav:
  - How To Create a Geocodes Server: local_stacks.md
  - List of services: stack_machines.md
  - Setup:
      - Services:
        - Base Machine: setting_up_services/setup_base_machine_configuration.md
        - Create Services Containers: setting_up_services/setup_geocodes_services_containers.md
        - Create Gleaner Containers: setting_up_services/setup_gleaner_container.md
      - Test Data:
        - Load Data: data_loading/indexing_with_gleanerio_for_testing.md
      - User Interface:
        - Create Geocodes UI Containers: setting_up_user_interface/setup_geocodes_ui_containers.md
        - Creating a Community Instance (Tenant): setting_up_user_interface/tenant
  - Load and Manage Production Data:
      - Load Data: data_loading/setup_indexing_with_gleanerio.md
  - Production:
      - Production: production
      - Creating and Loading Production: production/creatingAndLoadingProduction.md
      - Manage Services: production/managing_services.md
  - Tooling:
      - Install Glcon: install_glcon.md
      - Earthcube Utilities:
          - Overview: https://earthcube.github.io/earthcube_utilities/
          - Earthcube Utilities: https://earthcube.github.io/earthcube_utilities/earthcube_utilities/
          - Summarize: https://earthcube.github.io/earthcube_utilities/summarize/
  - Development:
      - User Interface: development/local_stacks.md
  - Help:
    -        Some SPARQL Queries: production/sparql.md
    - Troubleshooting: troubleshooting.md
