site_name: Geocodes Documentation
theme:
#  name: 'readthedocs'
  name: material
  features:
#    - content.code.copy
    - navigation.sections
markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences


plugins:
  - search
  # literate_nav must load after multirepo for the features to be available.
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
  -  mermaid2
  - literate-nav
  #https://pypi.org/project/mkdocs-jupyter/
  -  mkdocs-jupyter
  - callouts
nav:
  - Home: index.md
  - List of services: stack_machines.md
  - Setup:
      - Base Machine: setup_base_machine_configuration.md
      - Load Data: setup_indexing_with_gleanerio.md
      - Services and Geocodes UI: setup_geocodes_services_containers.md
      - Creating a Community Instance (Tenant): tenant
  - Load and Manage Production Data:
      - Production: production
  - Testing and Validation: indexing_with_gleanerio_for_testing.md
  - Tooling:
      - Install Glcon: install_glcon.md
  - Troubleshooting: troubleshooting.md
