#####################
#
# THIS SHOULD ONLY BE USED ONCE PER DOCKER SWARM SERVER.
#  IT INCLUDES A FIXED TRAEFIK Routing names: prod-server, prod-client, nb
# and HOST NAME 'geocodes.earthcube.org'
#
##########
version: '3.3'
networks:
  traefik_proxy:
    external: true
configs:
  facets_config:
    external: true

services:
  # the base routes:
  # geocodes /
  # vue services: /ec/api
  # notebook proxy: /notebook

  # this needs to be run with the services-compose file
  # docker-compose --.env-file .env.{yourcongig} -f service-compose.yaml -f geocodes-compose.yaml up -d
  # .env needs to contain
  ## GC_CLIENT_DOMAIN
  ## MINIO_SERVICE_ACCESS_KEY
  ## MINIO_SERVICE_SECRET_KEY
  # for Nobebook proxy
  ## GC_GITHUB_SECRET=OAUTH SECRET
  ## GC_GITHUB_CLIENTID=OAUTH APP ID
  ## GC_NB_AUTH_MODE=service


  vue-services:
    image: nsfearthcube/ec_facets_api_nodejs:latest
    #    profiles: ["geocodes"]
    #build: ./server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - S3ADDRESS=${GLEANER_OSS_DOMAIN}
      - S3KEY=${MINIO_ROOT_ACCESS_KEY}
      - S3SECRET=${MINIO_ROOT_SECRET_KEY}
      - S3SSL=${S3SSL}
      - S3PORT=${S3PORT}
      - BUCKET=${BUCKET}
      - BUCKETPATH=${BUCKETPATH}
      #      - PATHTEMPLATE=${PATHTEMPLATE}
      #      - TOOLTEMPLATE=${TOOLTEMPLATE}
      - TOOLPATH=${TOOLPATH}
      - TOOLREPO=${TOOLREPO}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prod-server.entrypoints=http"
      - "traefik.http.routers.prod-server.priority=90"
      - "traefik.http.routers.prod-server.rule=Host(`${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}`,  `geocodes.earthcube.org`) && PathPrefix(`/ec/api`)"
      #      - "traefik.http.routers.prod-server.rule=Host(`${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}`)  && PathPrefix(`/ec/api`)"
      - "traefik.http.middlewares.prod-server-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.prod-server.middlewares=prod-server-https-redirect"
      - "traefik.http.routers.prod-server-secure.priority=91"
      - "traefik.http.routers.prod-server-secure.entrypoints=https"
      - "traefik.http.routers.prod-server-secure.rule=Host(`${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}`, `geocodes.earthcube.org`) && PathPrefix(`/ec/api`)"
      #      - "traefik.http.routers.prod-server-secure.rule=Host(`${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}`) && PathPrefix(`/ec/api`)"
      - "traefik.http.routers.prod-server-secure.tls=true"
      - "traefik.http.routers.prod-server-secure.tls.certresolver=httpresolver"
      - "traefik.http.routers.prod-server-secure.service=prod-server"
      - "traefik.http.services.prod-server.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.middlewares.prod-server.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.prod-server.headers.accesscontrolalloworigin=*"
      - "traefik.http.middlewares.prod-server.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.prod-server.headers.addvaryheader=true"
      - "traefik.http.middlewares.ecapi_prefix_b.StripPrefix.prefixes=/ec/api"
      - "traefik.http.routers.prod-server-secure.middlewares=ecapi_prefix_b"
    networks:
      - traefik_proxy

  vue-client:
    image: nsfearthcube/ec_facets_client:latest
    #    profiles: ["geocodes"]
    restart: unless-stopped
    #build: ./client
    environment:
      - NODE_ENV=geocodestest
      - DOMAIN=https://${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}/
    configs:
      - source:   facets_config
        target: /usr/src/app/dist/public/config/config.yaml
      - source:   facets_config
        target: /usr/src/app/dist/config/config.yaml
    #      uid: '103'
    #      gid: '103'
    #      mode: 0440
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prod-client.entrypoints=http"
      - "traefik.http.routers.prod-client.priority=13"
      - "traefik.http.routers.prod-client.rule=Host(`${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}`, `geocodes.earthcube.org`)"
      #      - "traefik.http.routers.prod-client.rule=Host(`${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}`) "
      - "traefik.http.middlewares.prod-client-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.prod.middlewares=prod-client-https-redirect"
      - "traefik.http.routers.prod-client-secure.entrypoints=https"
      - "traefik.http.routers.prod-client-secure.priority=12"
      - "traefik.http.routers.prod-client-secure.rule=Host(`${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}`, `geocodes.earthcube.org`)"
      #      - "traefik.http.routers.prod-client-secure.rule=Host(`${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}`)"
      - "traefik.http.routers.prod-client-secure.tls=true"
      - "traefik.http.routers.prod-client-secure.tls.certresolver=httpresolver"
      - "traefik.http.routers.prod-client-secure.service=prod-client"
      - "traefik.http.services.prod-client.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.middlewares.prod-client.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.prod-client.headers.accesscontrolalloworigin=*"
      - "traefik.http.middlewares.prod-client.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.prod-client.headers.addvaryheader=true"
    networks:
      - traefik_proxy
  notebook-proxy:
    image: nsfearthcube/mknb:latest
    #    profiles: ["geocodes"]
    restart: unless-stopped
    #build: ./client
    environment:
      - AUTH_MODE=${GC_NB_AUTH_MODE}
      - GITHUB_SECRET=${GC_GITHUB_SECRET}
      - GITHUB_CLIENTID=${GC_GITHUB_CLIENTID}
      - GITHUB_USER==${GC_GITHUB_USER}
      - GITHUB_TOKEN=${GC_GITHUB_GITHUB_TOKEN}
      #GC_NB_AUTH_MODE=apikey
      - DOMAIN=https://${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prod-nb.entrypoints=http"
      - "traefik.http.routers.prod-nb.priority=90"
      - "traefik.http.routers.prod-nb.rule=Host(`${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}`, `geocodes.earthcube.org`) && PathPrefix(`/notebook`)"
      #      - "traefik.http.routers.prod-nb.rule=Host(`${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}`) && PathPrefix(`/notebook`)"
      - "traefik.http.middlewares.prod-nb-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.prod-nb.middlewares=prod-nb-https-redirect"
      - "traefik.http.routers.prod-nb-secure.entrypoints=https"
      - "traefik.http.routers.prod-nb-secure.priority=90"
      - "traefik.http.routers.prod-nb-secure.rule=Host(`${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}`, `geocodes.earthcube.org`) && PathPrefix(`/notebook`)"
      #      - "traefik.http.routers.prod-nb-secure.rule=Host(`${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}`) && PathPrefix(`/notebook`)"
      - "traefik.http.routers.prod-nb-secure.tls=true"
      - "traefik.http.routers.prod-nb-secure.tls.certresolver=httpresolver"
      - "traefik.http.routers.prod-nb-secure.service=prod-nb"
      - "traefik.http.services.prod-nb.loadbalancer.server.port=3031"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.middlewares.prod-nb.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.prod-nb.headers.accesscontrolalloworigin=*"
      - "traefik.http.middlewares.prod-nb.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.prod-nb.headers.addvaryheader=true"
      - "traefik.http.middlewares.prod-nb_prefix.StripPrefix.prefixes=/notebook"
      - "traefik.http.routers.prod-nb-secure.middlewares=prod-nb_prefix"
    networks:
      - traefik_proxy
#####################
#
# THIS SHOULD ONLY BE USED ONCE PER DOCKER SWARM SERVER.
#  IT INCLUDES A FIXED TRAEFIK Routing names: prod-server, prod-client, nb
# and HOST NAME 'geocodes.earthcube.org'
#
##########
