version: '3'
services:
  # the base routes:
  # geocodes /
  # vue services: /ec/api
  # notebook proxy: /notebook

  # this needs to be run with the services-compose file
  # docker-compose --.env-file .env.{yourcongig} -f service-compose.yaml -f geocodes-compose.yaml up -d
  # .env needs to contain
  ## GC_CLIENT_DOMAIN
  ## MINIO_SERVICE_ACCESS_KEY
  ## MINIO_SERVICE_SECRET_KEY
  # for Nobebook proxy
  ## GC_GITHUB_SECRET=OAUTH SECRET
  ## GC_GITHUB_CLIENTID=OAUTH APP ID
  ## GC_NB_AUTH_MODE=service


  vue-services:
    #image: nsfearthcube/ec_facets_api_nodejs:latest
    build: ./server
    restart: unless-stopped
    ports:
    - 3000:3000
    environment:
      - NODE_ENV=production
      - S3ADDRESS=s3system:9000
      - GLEANER_OSS_CONSOLE_DOMAIN=${GLEANER_OSS_CONSOLE_DOMAIN}
      - S3KEY=${MINIO_ROOT_ACCESS_KEY}
      - S3SECRET=${MINIO_ROOT_SECRET_KEY}
      - S3SSL=${S3SSL}
      - S3PORT=${S3PORT]
      - BUCKET=${BUCKET]
      - BUCKETPATH=${BUCKETPATH}
      - PATHTEMPLATE=${PATHTEMPLATE]
      - TOOLTEMPLATE=${TOOLTEMPLATE}
      - TOOLPATH=${TOOLPATH]
      - TOOLREPO=${TOOLREPO]

    networks:
      - traefik_proxy

  vue-client:
    #image: nsfearthcube/ec_facets_client:latest
    restart: unless-stopped
    build: ./client
    environment:
      - NODE_ENV=production
      - DOMAIN=http://localhost:8080/
    ports:
      - 8080:8080

    networks:
      - traefik_proxy
  notebook-proxy:
    image: nsfearthcube/mknb:latest
    restart: unless-stopped
    #build: ./client
    environment:
      - AUTH_MODE=${GC_NB_AUTH_MODE}
      - GITHUB_SECRET=${GC_GITHUB_SECRET}
      - GITHUB_CLIENTID=${GC_GITHUB_CLIENTID}
      - GITHUB_USER==${GC_GITHUB_USER}
      - GITHUB_TOKEN=${GC_GITHUB_GITHUB_TOKEN}
      #GC_NB_AUTH_MODE=apikey
      - DOMAIN=http://${GC_CLIENT_DOMAIN:?GC_CLIENT_DOMAIN environment variable is required}/
    ports:
      - 3031:3031
    networks:
      - traefik_proxy
networks:
  traefik_default:
