version: '3.5'
# This will need to be run from the chell until poraint 2.16 is relases
# this needs to incread the shareed memory

# ${GLEANER_ADMIN_DOMAIN}
# ${GLEANER_OSS_DOMAIN}
# ${GLEANER_GRAPH_DOMAIN}

# ${MINIO_ACCESS_KEY}
# ${MINIO_SECRET_KEY}
#
# ${GLEANER_TRAEFIK}
# ${GLEANER_OBJECTS}
# ${GLEANER_GRAPH}
volumes:
  logs:
    external: true
networks:
  traefik_proxy:
    external: true
  headless:
    external: true
    name: ${GLEANERIO_HEADLESS_NETWORK:-headless_gleanerio}
services:
  ## traefik is now in the base-machine-compose.yaml
  ## this allows portainer to be proxied, and have an SSL certificate.

  headless:
    image: chromedp/headless-shell:latest
#    build:
#      context: .
#      shm_size: "2gb"
    restart: unless-stopped
    ports:
      - 9222:9222
    environment:
      - SERVICE_PORTS=9222
    labels:
      -  "traefik.enable=false"
      - "traefik.backend=headlesschrome"
      - "traefik.port=9222"
      - "traefik.http.routers.headlesschrome-${PROJECT:-eco}.entrypoints=http"
      - "traefik.http.routers.headlesschrome-${PROJECT:-eco}.priority=13"
      - "traefik.http.routers.headlesschrome-${PROJECT:-eco}.rule=Host(`headlesschrome.${HOST? HOST is required}`)"
      - "traefik.http.middlewares.headlesschrome-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.headlesschrome-${PROJECT:-eco}.middlewares=sched-https-redirect"
      - "traefik.http.routers.headlesschrome-${PROJECT:-eco}-secure.entrypoints=https"
      - "traefik.http.routers.headlesschrome-${PROJECT:-eco}-secure.priority=12"
      - "traefik.http.routers.headlesschrome-${PROJECT:-eco}-secure.rule=Host(`headlesschrome.${HOST? HOST is required}`)"
      - "traefik.http.routers.headlesschrome-${PROJECT:-eco}-secure.tls=true"
      - "traefik.http.routers.headlesschrome-${PROJECT:-eco}-secure.tls.certresolver=httpresolver"
      - "traefik.http.routers.headlesschrome-${PROJECT:-eco}-secure.service=headlesschrome-${PROJECT}"
      - "traefik.http.services.sched-${PROJECT:-eco}.loadbalancer.server.port=9222"
      - "traefik.docker.network=traefik_proxy"
    tmpfs:
       - /tmp:size=512M
    volumes:
     - type: tmpfs
       target: /dev/shm

    networks:
      - traefik_proxy
      -   headless
