version: '3.5'
# This will need to be run from the chell until poraint 2.16 is relases
# this needs to incread the shareed memory

# ${GLEANER_ADMIN_DOMAIN}
# ${GLEANER_OSS_DOMAIN}
# ${GLEANER_GRAPH_DOMAIN}

# ${MINIO_ACCESS_KEY}
# ${MINIO_SECRET_KEY}
#
# ${GLEANER_TRAEFIK}
# ${GLEANER_OBJECTS}
# ${GLEANER_GRAPH}
volumes:
  logs:
    external: true
networks:
  traefik_proxy:
    external: true

services:
  ## traefik is now in the base-machine-compose.yaml
  ## this allows portainer to be proxied, and have an SSL certificate.

  headless:
    image: chromedp/headless-shell:latest
#    build:
#      context: .
#      shm_size: "2gb"
    restart: unless-stopped
    shm_size: "2gb"
    labels:
      - "traefik.backend=headlesschrome"
      - "traefik.port=9222"
    ports:
      - 9222:9222
    environment:
      - SERVICE_PORTS=9222
    networks:
      - traefik_proxy
