version: '3'

# these need to be for local development.
# they need to remove the https:

# initial starting point was gleaner: https://github.com/gleanerio/gleaner/blob/master/deployment/gleaner-DS-traefik.yml

# ${GLEANER_ADMIN_DOMAIN}
# ${GLEANER_OSS_DOMAIN}
# ${GLEANER_GRAPH_DOMAIN}

# ${MINIO_ACCESS_KEY}
# ${MINIO_SECRET_KEY}
#
# ${GLEANER_TRAEFIK}
# ${GLEANER_OBJECTS}
# ${GLEANER_GRAPH}
volumes:
  minio:
    external: true
  graph:
    external: true
  logs:
    external: true
services:
  # local, no router needed
#  traefik:
#    image: traefik:v2.10
#    container_name: traefik
#    restart: unless-stopped
#    security_opt:
#      - no-new-privileges:true
#    networks:
#      - traefik_proxy
#    ports:
#      - 8888:80   # can use the
# #     - 8443:443
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./traefik-data:/etc/traefik
#      #      - ./traefik-data/traefik.yml:/traefik.yml:ro
#      # issues with acme.json being created as  directory
#      #      - ./traefik-data/acme/acme.json:/acme.json
#      #      - ./traefik-data/acme:/etc/traefik/acme/
##      - ./traefik-data/logs:/logs
##      -  ./traefik-data/traefik.yml:/traefik.yml:ro
##      - ./traefik-data/acme/acme.json:/acme.json
#      - ${GLEANER_TRAEFIK}/logs:/logs
# #     -  ${GLEANER_TRAEFIK_YML}/traefik.yml:/traefik.yml:ro
##      - ${GLEANER_TRAEFIK}/acme/acme.json:/acme.json


#########
# blazegraph proxies well. /blazgraph is the route to the ui, and the services
#  localhost:8888/blazegraph
#############
  graph:
    image: nsfearthcube/blazegraph
    environment:
      JAVA_XMS: 2g
      JAVA_XMX: 8g
      JAVA_OPTS: -Xmx6g -Xms2g --XX:+UseG1GC
    ports:
    - 9999:9999

    volumes:
      - ${GLEANER_GRAPH}:/var/lib/blazegraph
    networks:
      - traefik_proxy

######
## the s3 system does not proxy by path
# localhost:9000    buckets
# localhost:9001  admin console
#####
  s3system:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    labels:
      - "traefik.enable=false"

    volumes:
      - ${GLEANER_OBJECTS:?GLEANER_OBJECTS environment variable is required}:/data
    environment:
      -  MINIO_ROOT_USER=${MINIO_ROOT_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_SECRET_KEY}
    networks:
      - traefik_proxy
#    command: ["server", "/data"]
    command: server /data --console-address ":9001"

  sparqlgui:
    image: erikap/yasgui
    restart: unless-stopped
    environment:
      DEFAULT_SPARQL_ENDPOINT: "https://`${GLEANER_GRAPH_DOMAIN}/${SPARQL_DEFAULT_SPARQL_ENDPOINT_PATH}`"
    ports:
      - 8888:80

    networks:
      - traefik_proxy
networks:
  traefik_proxy:
